# Generated by Django 5.0.2 on 2024-02-10 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cardapio', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pizza',
            name='foto',
            field=models.ImageField(upload_to='static/assets/pizzas/'),
        ),
    ]
